name: Build and Release Debian Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-deb:
    name: Build and release .deb for iframextract
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build Python wheel
        run: |
          python -m build --wheel --outdir dist/

      - name: Prepare .deb directory structure
        run: |
          rm -rf build/iframextract_deb
          mkdir -p build/iframextract_deb/DEBIAN
          mkdir -p build/iframextract_deb/usr/lib/iframextract
          mkdir -p build/iframextract_deb/usr/bin
          mkdir -p build/iframextract_deb/usr/share/man/man1

          # Copy DEBIAN control files
          cp debian/control build/iframextract_deb/DEBIAN/control
          if [ -f debian/postinst ]; then cp debian/postinst build/iframextract_deb/DEBIAN/postinst; fi
          if [ -f debian/rules ]; then cp debian/rules build/iframextract_deb/DEBIAN/rules; fi
          chmod 755 build/iframextract_deb/DEBIAN/*

          # Install Python package
          python3 -m pip install dist/*.whl --target build/iframextract_deb/usr/lib/iframextract

          # Copy launcher script
          cp debian/iframextract build/iframextract_deb/usr/bin/iframextract
          chmod +x build/iframextract_deb/usr/bin/iframextract

          # Add man page
          cp debian/docs/iframextract.1 build/iframextract_deb/usr/share/man/man1/
          gzip -9 build/iframextract_deb/usr/share/man/man1/iframextract.1

      - name: Build .deb package
        run: |
          dpkg-deb --build build/iframextract_deb dist/

      - name: Upload Debian package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iframextract-deb
          path: dist/*.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# name: Build and Release Debian Package

# on:
#   push:
#     tags:
#       - "v*"
#   workflow_dispatch:

# jobs:
#   build-deb:
#     name: Build and release .deb for iframextract
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python 3.11
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.11"

#       - name: Install Python build dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install build

#       - name: Build Python wheel
#         run: python -m build --wheel --outdir dist/

#       - name: Prepare Debian packaging directory and install wheel
#         run: |
#           # Clean previous build folder if any
#           rm -rf build/iframextract_deb

#           # Create target folder for Debian package
#           mkdir -p build/iframextract_deb/usr/lib/iframextract

#           # Copy your existing debian directory into build folder
#           cp -r debian build/iframextract_deb/

#           # Install the built wheel into the /usr/lib/iframextract directory inside build folder
#           python3 -m pip install dist/*.whl --target build/iframextract_deb/usr/lib/iframextract

#           # Make launcher script executable (assuming debian/iframextract is your launcher script)
#           chmod +x build/iframextract_deb/debian/iframextract

#       - name: Build .deb package
#         run: |
#           # Rename debian directory to DEBIAN (required by dpkg-deb)
#           mv build/iframextract_deb/debian build/iframextract_deb/DEBIAN

#           # Build the Debian package
#           dpkg-deb --build build/iframextract_deb dist/iframextract_1.0.0_all.deb

#       - name: Upload Debian package as artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: iframextract-deb
#           path: dist/*.deb

#       - name: Create GitHub Release and upload .deb
#         id: create_release
#         uses: softprops/action-gh-release@v1
#         with:
#           files: dist/*.deb
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
