name: Build and Release Debian Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deb:
    name: Build and release .deb for iframextract
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build Python wheel
        run: |
          python -m build --wheel --outdir dist/

      - name: Prepare .deb directory structure
        run: |
          mkdir -p build/iframextract_deb/DEBIAN
          mkdir -p build/iframextract_deb/usr/bin
          mkdir -p build/iframextract_deb/usr/lib/iframextract
          mkdir -p build/iframextract_deb/usr/share/man/man1

          # Install the wheel contents to the custom location
          python3 -m pip install dist/*.whl --target build/iframextract_deb/usr/lib/iframextract

          # Copy the CLI launcher script
          echo '#!/usr/bin/env python3\nfrom iframextract.cli import main\nif __name__ == "__main__":\n    main()' > build/iframextract_deb/usr/bin/iframextract
          chmod +x build/iframextract_deb/usr/bin/iframextract

          # Add man page
          cp docs/iframextract.1 build/iframextract_deb/usr/share/man/man1/
          gzip -9 build/iframextract_deb/usr/share/man/man1/iframextract.1

          # Create control file
          echo 'Package: iframextract\nVersion: 1.0.0\nSection: utils\nPriority: optional\nArchitecture: all\nDepends: python3\nMaintainer: Mahros <your.email@example.com>\nDescription: CLI tool to extract <iframe> elements from HTML\n' > build/iframextract_deb/DEBIAN/control

      - name: Build .deb package
        run: |
          dpkg-deb --build build/iframextract_deb dist/

      - name: Upload Debian package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: iframextract-deb
          path: "dist/*.deb"
