name: Build and Release Debian Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build Python wheel
        run: |
          python -m build --wheel --outdir dist/

      - name: Prepare Debian package structure
        run: |
          mkdir -p build/iframextract_deb/DEBIAN
          mkdir -p build/iframextract_deb/usr/lib/iframextract
          mkdir -p build/iframextract_deb/usr/bin
          mkdir -p build/iframextract_deb/usr/share/man/man1

          # Copy Debian control file
          cp debian/control build/iframextract_deb/DEBIAN/control

          # Copy wheel contents to /usr/lib/iframextract
          python3 -m pip install dist/*.whl --target build/iframextract_deb/usr/lib/iframextract

          # Install CLI launcher
          cp debian/iframextract build/iframextract_deb/usr/bin/iframextract
          chmod +x build/iframextract_deb/usr/bin/iframextract

          # Install man page
          cp docs/iframextract.1 build/iframextract_deb/usr/share/man/man1/
          gzip -9 build/iframextract_deb/usr/share/man/man1/iframextract.1

      - name: Build .deb package
        run: |
          dpkg-deb --build build/iframextract_deb dist/

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: iframextract-deb
          path: dist/*.deb
